spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Bookflix
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  web:
    locale: pt_BR
    locale-resolver: fixed

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  error:
    include-message: always